name: tf_kd
pep_version: 2.0.0
sample_table: sample_table.csv
subsample_table: subsample_table.csv

sample_modifiers:
  derive:
      attributes: [path_r1, path_r2]
      sources:
        amarel_novo_r1: /projects/genetics/ellison_lab/data/illumina/RNAseq/novogene_20220425/usftp21.novogene.com/raw_data/{fq_r1}
        amarel_novo_r2: /projects/genetics/ellison_lab/data/illumina/RNAseq/novogene_20220425/usftp21.novogene.com/raw_data/{fq_r2}
        amarel_novo2_r1: /projectsp/genetics/ellison_lab/matt/data/220809_tetf_kd-rnd2-batch1/01.RawData/{fq_r1}
        amarel_novo2_r2: /projectsp/genetics/ellison_lab/matt/data/220809_tetf_kd-rnd2-batch1/01.RawData/{fq_r2}
        amarel_novo3_r1: /projectsp/genetics/ellison_lab/matt/data/221003_tetf_kd-round2-batch2-01/01.RawData/{fq_r1}
        amarel_novo3_r2: /projectsp/genetics/ellison_lab/matt/data/221003_tetf_kd-round2-batch2-01/01.RawData/{fq_r2}
        amarel_novo4_r1: /projectsp/genetics/ellison_lab/matt/data/230221_pangolin_germline_kd/01.RawData/{fq_r1}
        amarel_novo4_r2: /projectsp/genetics/ellison_lab/matt/data/230221_pangolin_germline_kd/01.RawData/{fq_r2}